### PR TITLE
refactorings

### PR DESCRIPTION
**Pull request by matzew**
Done for AGPUSH-1394

@lfryc mind to review?

### CODE REVIEW

**Comment by sebastienblanc** [comment]
:+1:

**Comment by lfryc** [comment]
:eyes:

**Comment by matzew** [comment]
ready to merge, @lfryc @sebastienblanc ?

**Comment by lfryc** [comment]
Yep, reviewed, tested, merging..

**Comment by lfryc** [comment]
:rocket: Landed!

**Pull request merged**
