### PR TITLE
Updated pom.xml, it had some errors with dependencies

### PR DESCRIPTION
**Pull request by bismoy2013**

### CODE REVIEW

**Comment by matzew** [comment]
@bismoy2013 what's the error you got ?

**Comment by bismoy2013** [comment]
@matzew some compilation error in the xml file.

**Comment by matzew** [comment]
mind sharing the stack trace  ?

**Comment by bismoy2013** [comment]
You can check in the master branch of the codebase, you should be able to see that error in pom.xml (if I'm not wrong) .

**Comment by matzew** [comment]
@bismoy2013 works fine (w. Maven 3.2.3):
```
mvn -v
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /Apache/maven/current
Java version: 1.8.0_20, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"
```

Trying now with an empty M2 Repo

**Comment by bismoy2013** [comment]
Hmm no idea then, anyways no prob :)

**Comment by matzew** [comment]
are you saying it now also wrks for you ? :)

On Mon, Nov 23, 2015 at 9:07 AM, Bismoy Murasing <notifications@github.com>
wrote:

> Hmm no idea then, anyways no prob :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-java-client/pull/77#issuecomment-158873513>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
Ok... works w/ a clean/empty repo as well

**Comment by bismoy2013** [comment]
Since you said it works fine, didn't want to check again. It probably showed errors because of some IDE issues(I was using Spring Tool Suite), could be possible.

**Comment by matzew** [comment]
@bismoy2013 ok - are you guys interested in updating the wiki for list your company/project as users:

https://github.com/aerogear/aerogear-unifiedpush-server/wiki/Users-of-the-UnifiedPush-Server

**Comment by bismoy2013** [comment]
@matzew actually it's just me personally exploring aerogear, maybe you can also shed some light on my one question, does aerogear support background sync push notification in android ?

**Comment by matzew** [comment]
not sure, on the sync stuff - mind subscribing to our Developer list (see
infos hre: https://aerogear.org/community/#contact) and sending a question
via mail ? Our Android experts are working in US and BR

On Mon, Nov 23, 2015 at 10:51 AM, Bismoy Murasing <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> actually it's just me personally
> exploring aerogear, maybe you can also shed some light on my one question,
> does aerogear support background sync push notification in android ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-unifiedpush-java-client/pull/77#issuecomment-158890506>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request closed without merging**
